# Generated by Django 5.2.6 on 2025-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_artistic', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_arte', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='artistas/')),
                ('rede_social', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
